theme_color:
  primary: indigo
  accent: red

notice:

favicon: /images/favicon.png
banner: /images/banner.png
avatar: /images/avatar.jpg
rss: /atom.xml

email: liyong.use@gmail.com
sns:
  twitter:
  facebook:
  google_plus:
  weibo:
  instagram:
  tumblr:
  github: https://github.com/lyite
  linkedin:
  zhihu:
  douban:
  qq:
  wechat:

open_graph:
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:
site_verification:
  google:
  baidu:
analytics:
  google_site_id:
  baidu_site_id:
  cnzz_site_id:

pages:
- name: 时间轴
  link: /timeline
- name: 标签云
  link: /tagcloud
- name: 相册
  link: /gallery
- name: 电视直播
  link: /tv
links:
  #- name: ***
  #  link: http://***.com/

since: 2021
footer_text:
license:

gallery:
  fancybox_css: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.css
  fancybox_js: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.js
  jquery_js: https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js
  lazyload_js: https://cdn.bootcss.com/jquery_lazyload/1.9.7/jquery.lazyload.min.js
busuanzi:
  site: true
  page: true
  busuanzi_js: http://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
qrcode:
  caption: 发送到手机
  use: plugin
donate:
- name: 支付宝
  link: /images/alipay.jpg
- name: 微信支付
  link: /images/wechat.jpg
search:
  placeholder: 请输入关键字
  path: /search.xml
  use: plugin
comment:
  use: gitalk
  disqus_shortname:
  gitalk_client_id: f8bd9228d3e479c8728e
  gitalk_client_secret: 630e8a8360a817fdfe97395d63e0ed63cc24cbf7
  gitalk_repo: lyite.github.io
  gitalk_owner: lyite
  gitalk_sid_type: uuid
  livere_data_uid:
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  valine_sid_type:
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:
